plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
    id 'com.vanniktech.maven.publish' version '0.34.0'
}

group = 'com.king.wechat.qrcode'
version = '3.0.0'

configurations {
    bundled
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

compileJava {
    options.encoding = 'UTF-8'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    bundled files('lib/opencv-500.jar')
    compileOnly files('lib/opencv-500.jar')
    testImplementation files('lib/opencv-500.jar')
    implementation 'net.java.dev.jna:jna:5.17.0'
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveClassifier.set('')
    configurations = [project.configurations.bundled]
    mergeServiceFiles()
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}

tasks.named('jar', Jar) {
    archiveClassifier.set('plain')
}

tasks.named('assemble') {
    dependsOn tasks.named('shadowJar')
}

tasks.named('publishToMavenLocal') {
    dependsOn tasks.named('shadowJar')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Test).configureEach {
    systemProperty 'file.encoding', 'UTF-8'
    jvmArgs '-Dfile.encoding=UTF-8'
}
