VERSION_NAME=3.0.0
VERSION_CODE=16
GROUP=com.github.jenly1314.WeChatQRCode

POM_NAME=Wechat QRCode for Java
POM_ARTIFACT_ID=wechat-qrcode-java

POM_DESCRIPTION=Wechat QRCode
POM_URL=https://github.com/jenly1314/WeChatQRCode

POM_SCM_URL=https://github.com/jenly1314/WeChatQRCode
POM_SCM_CONNECTION=scm:git@github.com:jenly1314/WeChatQRCode.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:jenly1314/WeChatQRCode.git

#POM_LICENCE_NAME=The MIT License
#POM_LICENCE_URL=https://opensource.org/licenses/mit-license.php
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=jenly
POM_DEVELOPER_NAME=Jenly Yu
POM_DEVELOPER_URL=https://github.com/jenly1314/

mavenCentralPublishing=true
